name: Release Binary

on:
  push:
    tags:
      - 'v*'  # @note: Triggers only on version tags

permissions:
  contents: write
  discussions: write
  packages: write

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        
    - name: Build
      run: |
        mkdir -p bin/
        go build -v -o bin/git-hotswap.exe ./src
    
    - name: Generate Changelog
      id: changelog
      uses: metcalfc/changelog-generator@v4.5.0
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Release
      id: create_release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        make_latest: 'true'
        name: 'Version ${{ github.ref_name }}'
        body: |
          ## What's Changed
          ${{ steps.changelog.outputs.changelog }}
        files: bin/git-hotswap.exe